const DEMO_USER="kiran",DEMO_PASS="123";const KEY="priceTrackProducts";let products=loadProducts();let activeSection="overview";
const seed=[{id:1,name:"Apple AirPods Pro 2",price:18999,previous:19999,target:16999,store:"Amazon",url:"",added:Date.now()-86400000*4,history:[20999,20499,19999,19499,19999,18999,18999]},{id:2,name:"Sony WH-1000XM5",price:24990,previous:27990,target:22990,store:"Flipkart",url:"",added:Date.now()-86400000*7,history:[27990,27490,26990,26990,25990,25490,24990]},{id:3,name:"Samsung 55” 4K Smart TV",price:44999,previous:45999,target:39999,store:"Croma",url:"",added:Date.now()-86400000*2,history:[46999,45999,45999,44999,44999,45999,44999]}];
if(!products.length){products=seed;saveProducts();}
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function loadProducts(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}function saveProducts(){localStorage.setItem(KEY,JSON.stringify(products))}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}function pct(p){const c=p.price,old=p.previous||c;return old?Math.round((old-c)/old*100):0}
function showToast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function login(){const u=$("#username").value.trim(),p=$("#password").value; if(u===DEMO_USER&&p===DEMO_PASS){sessionStorage.setItem("priceTrackAuth","1");$("#loginScreen").classList.add("hidden");$("#app").classList.remove("hidden");renderAll()}else $("#loginError").textContent="Invalid username or password."}
function renderAll(){renderStats();renderDrops();renderProducts();renderHistory();drawChart()}
function renderStats(){const drops=products.filter(p=>p.price<p.previous);const savings=products.reduce((s,p)=>s+Math.max(0,p.previous-p.price),0);const best=products.length?Math.min(...products.map(p=>p.price)):0;$("#totalProducts").textContent=products.length;$("#priceDrops").textContent=drops.length;$("#savings").textContent=money(savings);$("#bestPrice").textContent=money(best)}
function renderDrops(){const el=$("#recentDrops");const list=[...products].filter(p=>p.price<p.previous).sort((a,b)=>pct(b)-pct(a)).slice(0,5);el.innerHTML=list.length?list.map(p=>`<div class="drop-item"><div class="product-dot">${p.name.charAt(0)}</div><div><strong>${esc(p.name)}</strong><small>${esc(p.store)} · ${money(p.price)}</small></div><span class="drop-percent">-${pct(p)}%</span></div>`).join(""):`<div class="muted" style="padding:25px 0;text-align:center;font-size:12px">No price drops yet.</div>`}
function renderProducts(){const q=$("#searchInput").value.toLowerCase(),sort=$("#sortSelect").value;let list=products.filter(p=>(p.name+" "+p.store).toLowerCase().includes(q));if(sort==="low")list.sort((a,b)=>a.price-b.price);if(sort==="high")list.sort((a,b)=>b.price-a.price);if(sort==="drop")list.sort((a,b)=>pct(b)-pct(a));if(sort==="recent")list.sort((a,b)=>b.added-a.added);$("#productGrid").innerHTML=list.length?list.map(p=>{const drop=p.price<p.previous;return`<article class="product-card"><div class="product-top"><div><h3>${esc(p.name)}</h3><span class="store">${esc(p.store)}</span></div><div class="product-dot">${p.name.charAt(0)}</div></div><div class="price">${money(p.price)}</div><div class="target">Target: <b>${money(p.target)}</b></div><span class="change ${drop?"down":"up"}">${drop?"↓ "+pct(p)+"% lower":"↑ "+Math.abs(pct(p))+"%"} vs previous</span><div class="product-actions">${p.url?`<button class="small-btn" onclick="window.open('${safeUrl(p.url)}','_blank')">Open store</button>`:""}<button class="small-btn" onclick="simulateUpdate(${p.id})">Update price</button><button class="small-btn" onclick="removeProduct(${p.id})">Delete</button></div></article>`}).join(""):`<div class="panel muted" style="grid-column:1/-1;text-align:center;padding:45px">No products found. Add your first tracker.</div>`}
function renderHistory(){const el=$("#historyTable");el.innerHTML=products.map(p=>{const d=p.price-p.previous,down=d<0;return`<tr><td><strong>${esc(p.name)}</strong><br><small class="muted">${esc(p.store)}</small></td><td>${money(p.price)}</td><td>${money(p.previous)}</td><td class="${down?"status":""}">${down?"↓ ":"↑ "}${money(Math.abs(d))}</td><td>${money(p.target)}</td><td><span class="status">${p.price<=p.target?"Target reached":"Tracking"}</span></td></tr>`}).join("")}
function drawChart(){const c=$("#priceChart"),ctx=c.getContext("2d"),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);let days=Number($("#chartRange").value),series=Array.from({length:days},(_,i)=>{const vals=products.map(p=>{const his=p.history||[p.price];return his[Math.max(0,his.length-days+i)]??p.price});return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0});if(!series.length||!products.length){return}const max=Math.max(...series),min=Math.min(...series),pad=25;ctx.strokeStyle="#e8eaf0";ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad+(h-pad*2)*i/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}const range=max-min||1;ctx.beginPath();series.forEach((v,i)=>{const x=pad+(w-pad*2)*i/(series.length-1||1),y=pad+(h-pad*2)*(1-(v-min)/range);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle="#6d5dfc";ctx.lineWidth=3;ctx.stroke();ctx.lineTo(w-pad,h-pad);ctx.lineTo(pad,h-pad);ctx.closePath();ctx.fillStyle="rgba(109,93,252,.08)";ctx.fill();ctx.fillStyle="#7c8190";ctx.font="10px Inter";ctx.fillText(money(Math.round(max)),pad,13);ctx.fillText(money(Math.round(min)),pad,h-3)}
function openModal(){$("#modal").classList.remove("hidden");$("#productName").focus()}function closeModal(){$("#modal").classList.add("hidden");$("#productForm").reset()}
function addProduct(e){e.preventDefault();const price=Number($("#productPrice").value),target=Number($("#targetPrice").value);products.unshift({id:Date.now(),name:$("#productName").value.trim(),price,previous:price,target,store:$("#productStore").value.trim(),url:$("#productUrl").value.trim(),added:Date.now(),history:[price]});saveProducts();closeModal();renderAll();showToast("Product added successfully.")}
function removeProduct(id){if(!confirm("Remove this product from tracking?"))return;products=products.filter(p=>p.id!==id);saveProducts();renderAll();showToast("Product removed.")}
function simulateUpdate(id){const p=products.find(x=>x.id===id);if(!p)return;p.previous=p.price;const variation=(Math.random()-.45)*.12;p.price=Math.max(1,Math.round(p.price*(1+variation)));p.history=[...(p.history||[]),p.price].slice(-30);saveProducts();renderAll();showToast("Price updated (demo data).")}
function switchSection(name){activeSection=name;$$(".section").forEach(s=>s.classList.add("hidden"));$("#"+name+"Section").classList.remove("hidden");$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.section===name));$("#pageTitle").textContent=name[0].toUpperCase()+name.slice(1);if(name==="overview")drawChart()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function safeUrl(s){return /^https?:\\/\\//i.test(s)?s:"#"}
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();login()});$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("priceTrackAuth");location.reload()};$("#addProductBtn").onclick=openModal;$("#addProductHero").onclick=openModal;$("#closeModal").onclick=closeModal;$("#productForm").addEventListener("submit",addProduct);$("#searchInput").addEventListener("input",renderProducts);$("#sortSelect").addEventListener("change",renderProducts);$("#chartRange").addEventListener("change",drawChart);$("#refreshBtn").onclick=()=>{products.forEach(p=>simulateUpdate(p.id));showToast("All prices refreshed.")};$$(".nav-item").forEach(b=>b.onclick=()=>switchSection(b.dataset.section));window.addEventListener("resize",()=>activeSection==="overview"&&drawChart());
if(sessionStorage.getItem("priceTrackAuth")==="1"){$("#loginScreen").classList.add("hidden");$("#app").classList.remove("hidden");renderAll()}